name: tutorial-seurat-conda
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - r-seurat
